#!/bin/bash

INPUT_PATH="$1"
echo "-> Sending $INPUT_PATH to Disposable VM..." >&2
rm /tmp/tar -f
tar -cf /tmp/tar "$INPUT_PATH"
cat /tmp/tar
echo "-> any output from call:" >&2
exec cat >&$SAVED_FD_1
echo "-> Done..." >&2

