#!/bin/bash

# receives file, untar and push

TMP_DIR=$(mktemp --tmpdir --directory git-repo-XXXXXXXX)

# Get the original data
cat | tar -C "$TMP_DIR" -xf -

# cd and push
cd $(ls -d $TMP_DIR/.??*) && git push

# cleanup
cd /
rm -rf "$TMP_DIR"


